app1/urls.py
from django.urls import path
from app1.views import *
app_name='aaa'

urlpatterns=[
    path('hi/',hi,name='hi'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='bbb'

urlpatterns=[
    path('bye/',bye,name='bye'),
]

project5/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hi(request):
    return render(request,'hi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def bye(request):
    return render(request,'bye.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Bye Bye Django</h1>
       <a href="{% url 'aaa:hi' %}">navigate to hi</a>
    </center>
</body>
</html>

templates/hi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hi hloo Django</h1>
        <a href="{% url 'bbb:bye' %}">navigate to bye</a>
       
    </center>
</body>
</html>